version: '3.7'

services:
  runner: &runner
    environment:
      REDIS_URL: redis://redis:6379/
      HISTFILE: /usr/local/hist/.bash_history
      IRB_HISTFILE: /usr/local/hist/.irb_history
      EDITOR: vi

      # MEMORIAM_TV_PRIVATE_API_URL: ${MEMORIAM_TV_PRIVATE_API_URL:?}
      # MEMORIAM_TV_WARN_LEVEL: ${MEMORIAM_TV_WARN_LEVEL:?}
      # MEMORIAM_TV_MINIMUM_REDIS_MEMORY: ${MEMORIAM_TV_MINIMUM_REDIS_MEMORY:?}
      # SLACK_HOOK: ${SLACK_HOOK:?}

    build:
      context: .devcontainer
      args:
        RUBY_VERSION: 3.3.6
    command: /bin/bash
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - history:/usr/local/hist
    tmpfs:
      - /tmp
      - /app/tmp/pids
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:6.2-alpine
    volumes:
      - redis:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
    command: redis-server --save 20 1 --loglevel warning

volumes:
  bundle:
  redis:
  history:
